// CardRelay is a network protocol for proxying ISO 7816 APDUs between
// a client (host with a logical card session) and a server (host with
// physical access to the smart card via PC/SC).
//
// Wire model: a single bidirectional stream represents one card
// session. The client sends APDU requests, the server forwards them
// to its locally-attached card, and returns responses. When either
// side closes the stream the server releases the underlying card
// connection — so session lifecycle is implicit in stream lifecycle,
// no session_id management.
//
// What this protocol does NOT do:
//
//   - Authenticate the caller. Anyone who can reach the gRPC port
//     and pass mTLS can drive APDUs at the card. A real deployment
//     pairs CardRelay with a separate authorization layer (per-
//     operation capability tokens, attested workload identity,
//     etc). Without that layer, exposing a PIN-verified PIV applet
//     over CardRelay is equivalent to handing the caller a signing
//     oracle.
//
//   - Encrypt the APDUs end-to-end. CardRelay relies on transport
//     security (TLS / mTLS) between client and server, but the
//     server sees plaintext APDUs. If the client and server cannot
//     trust each other to that degree, CardRelay is the wrong tool;
//     use SCP11 directly between client and card, with CardRelay
//     forwarding the already-wrapped APDUs (which is supported —
//     see the raw bytes mode below).
//
//   - Multiplex card sessions. One stream = one session = one
//     reader. To use N readers concurrently, open N streams.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: cardrelay.proto

package cardrelayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CardRelay_Session_FullMethodName = "/cardrelay.v1.CardRelay/Session"
)

// CardRelayClient is the client API for CardRelay service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CardRelayClient interface {
	// Session opens a bidirectional stream that maps to a single
	// card-session lifetime on the server. The first message MAY be
	// a HelloRequest carrying optional reader-selection criteria;
	// subsequent messages are APDU transmits. Closing the client
	// half of the stream signals the server to release the card.
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
}

type cardRelayClient struct {
	cc grpc.ClientConnInterface
}

func NewCardRelayClient(cc grpc.ClientConnInterface) CardRelayClient {
	return &cardRelayClient{cc}
}

func (c *cardRelayClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CardRelay_ServiceDesc.Streams[0], CardRelay_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CardRelay_SessionClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

// CardRelayServer is the server API for CardRelay service.
// All implementations must embed UnimplementedCardRelayServer
// for forward compatibility.
type CardRelayServer interface {
	// Session opens a bidirectional stream that maps to a single
	// card-session lifetime on the server. The first message MAY be
	// a HelloRequest carrying optional reader-selection criteria;
	// subsequent messages are APDU transmits. Closing the client
	// half of the stream signals the server to release the card.
	Session(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	mustEmbedUnimplementedCardRelayServer()
}

// UnimplementedCardRelayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCardRelayServer struct{}

func (UnimplementedCardRelayServer) Session(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedCardRelayServer) mustEmbedUnimplementedCardRelayServer() {}
func (UnimplementedCardRelayServer) testEmbeddedByValue()                   {}

// UnsafeCardRelayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CardRelayServer will
// result in compilation errors.
type UnsafeCardRelayServer interface {
	mustEmbedUnimplementedCardRelayServer()
}

func RegisterCardRelayServer(s grpc.ServiceRegistrar, srv CardRelayServer) {
	// If the following call panics, it indicates UnimplementedCardRelayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CardRelay_ServiceDesc, srv)
}

func _CardRelay_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CardRelayServer).Session(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CardRelay_SessionServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

// CardRelay_ServiceDesc is the grpc.ServiceDesc for CardRelay service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CardRelay_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cardrelay.v1.CardRelay",
	HandlerType: (*CardRelayServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _CardRelay_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "cardrelay.proto",
}
