// CardRelay is a network protocol for proxying ISO 7816 APDUs between
// a client (host with a logical card session) and a server (host with
// physical access to the smart card via PC/SC).
//
// Wire model: a single bidirectional stream represents one card
// session. The client sends APDU requests, the server forwards them
// to its locally-attached card, and returns responses. When either
// side closes the stream the server releases the underlying card
// connection — so session lifecycle is implicit in stream lifecycle,
// no session_id management.
//
// What this protocol does NOT do:
//
//   - Authenticate the caller. Anyone who can reach the gRPC port
//     and pass mTLS can drive APDUs at the card. A real deployment
//     pairs CardRelay with a separate authorization layer (per-
//     operation capability tokens, attested workload identity,
//     etc). Without that layer, exposing a PIN-verified PIV applet
//     over CardRelay is equivalent to handing the caller a signing
//     oracle.
//
//   - Encrypt the APDUs end-to-end. CardRelay relies on transport
//     security (TLS / mTLS) between client and server, but the
//     server sees plaintext APDUs. If the client and server cannot
//     trust each other to that degree, CardRelay is the wrong tool;
//     use SCP11 directly between client and card, with CardRelay
//     forwarding the already-wrapped APDUs (which is supported —
//     see the raw bytes mode below).
//
//   - Multiplex card sessions. One stream = one session = one
//     reader. To use N readers concurrently, open N streams.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: cardrelay.proto

package cardrelayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorResponse_Kind int32

const (
	ErrorResponse_UNKNOWN          ErrorResponse_Kind = 0
	ErrorResponse_NO_READER        ErrorResponse_Kind = 1 // Hello reader hint matched no reader.
	ErrorResponse_READER_GONE      ErrorResponse_Kind = 2 // Card removed mid-session.
	ErrorResponse_PROTOCOL_VERSION ErrorResponse_Kind = 3 // Hello protocol_version unsupported.
	ErrorResponse_TRANSPORT        ErrorResponse_Kind = 4 // Underlying card transport failed.
	ErrorResponse_INVALID_REQUEST  ErrorResponse_Kind = 5 // Malformed message.
)

// Enum value maps for ErrorResponse_Kind.
var (
	ErrorResponse_Kind_name = map[int32]string{
		0: "UNKNOWN",
		1: "NO_READER",
		2: "READER_GONE",
		3: "PROTOCOL_VERSION",
		4: "TRANSPORT",
		5: "INVALID_REQUEST",
	}
	ErrorResponse_Kind_value = map[string]int32{
		"UNKNOWN":          0,
		"NO_READER":        1,
		"READER_GONE":      2,
		"PROTOCOL_VERSION": 3,
		"TRANSPORT":        4,
		"INVALID_REQUEST":  5,
	}
)

func (x ErrorResponse_Kind) Enum() *ErrorResponse_Kind {
	p := new(ErrorResponse_Kind)
	*p = x
	return p
}

func (x ErrorResponse_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorResponse_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_cardrelay_proto_enumTypes[0].Descriptor()
}

func (ErrorResponse_Kind) Type() protoreflect.EnumType {
	return &file_cardrelay_proto_enumTypes[0]
}

func (x ErrorResponse_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorResponse_Kind.Descriptor instead.
func (ErrorResponse_Kind) EnumDescriptor() ([]byte, []int) {
	return file_cardrelay_proto_rawDescGZIP(), []int{6, 0}
}

// ClientMessage is the union of everything a client sends on the
// stream. Exactly one field is set per message.
type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ClientMessage_Hello
	//	*ClientMessage_Transmit
	Body          isClientMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_cardrelay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cardrelay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_cardrelay_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetBody() isClientMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ClientMessage) GetHello() *HelloRequest {
	if x != nil {
		if x, ok := x.Body.(*ClientMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ClientMessage) GetTransmit() *TransmitRequest {
	if x != nil {
		if x, ok := x.Body.(*ClientMessage_Transmit); ok {
			return x.Transmit
		}
	}
	return nil
}

type isClientMessage_Body interface {
	isClientMessage_Body()
}

type ClientMessage_Hello struct {
	Hello *HelloRequest `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ClientMessage_Transmit struct {
	Transmit *TransmitRequest `protobuf:"bytes,2,opt,name=transmit,proto3,oneof"`
}

func (*ClientMessage_Hello) isClientMessage_Body() {}

func (*ClientMessage_Transmit) isClientMessage_Body() {}

// ServerMessage is the union of everything a server sends on the
// stream. Exactly one field is set per message.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ServerMessage_Hello
	//	*ServerMessage_Transmit
	//	*ServerMessage_Error
	Body          isServerMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_cardrelay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cardrelay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_cardrelay_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetBody() isServerMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerMessage) GetHello() *HelloResponse {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ServerMessage) GetTransmit() *TransmitResponse {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Transmit); ok {
			return x.Transmit
		}
	}
	return nil
}

func (x *ServerMessage) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isServerMessage_Body interface {
	isServerMessage_Body()
}

type ServerMessage_Hello struct {
	Hello *HelloResponse `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ServerMessage_Transmit struct {
	Transmit *TransmitResponse `protobuf:"bytes,2,opt,name=transmit,proto3,oneof"`
}

type ServerMessage_Error struct {
	Error *ErrorResponse `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*ServerMessage_Hello) isServerMessage_Body() {}

func (*ServerMessage_Transmit) isServerMessage_Body() {}

func (*ServerMessage_Error) isServerMessage_Body() {}

// HelloRequest is the optional first message that lets the client
// pick which reader to bind to on the server side. If omitted, the
// server uses its default reader.
type HelloRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Substring match on reader name. Empty = first available reader.
	Reader string `protobuf:"bytes,1,opt,name=reader,proto3" json:"reader,omitempty"`
	// Protocol version the client expects to speak. Mismatches let the
	// server reject the stream cleanly with ErrorResponse.
	ProtocolVersion uint32 `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_cardrelay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cardrelay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_cardrelay_proto_rawDescGZIP(), []int{2}
}

func (x *HelloRequest) GetReader() string {
	if x != nil {
		return x.Reader
	}
	return ""
}

func (x *HelloRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

// HelloResponse confirms the session is bound to a specific reader
// on the server side.
type HelloResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The actual reader name the server bound to. May differ from the
	// client's hint (substring match).
	Reader          string `protobuf:"bytes,1,opt,name=reader,proto3" json:"reader,omitempty"`
	ProtocolVersion uint32 `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_cardrelay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cardrelay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_cardrelay_proto_rawDescGZIP(), []int{3}
}

func (x *HelloResponse) GetReader() string {
	if x != nil {
		return x.Reader
	}
	return ""
}

func (x *HelloResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

// TransmitRequest carries one APDU. The client picks ONE of `apdu`
// or `raw`; the server picks the matching method on its underlying
// transport (Transmit vs TransmitRaw). raw is the right choice for
// already-wrapped SCP APDUs where the client is doing the secure-
// channel work and the server is just a pipe.
type TransmitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*TransmitRequest_Apdu
	//	*TransmitRequest_Raw
	Body          isTransmitRequest_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransmitRequest) Reset() {
	*x = TransmitRequest{}
	mi := &file_cardrelay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransmitRequest) ProtoMessage() {}

func (x *TransmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cardrelay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransmitRequest.ProtoReflect.Descriptor instead.
func (*TransmitRequest) Descriptor() ([]byte, []int) {
	return file_cardrelay_proto_rawDescGZIP(), []int{4}
}

func (x *TransmitRequest) GetBody() isTransmitRequest_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *TransmitRequest) GetApdu() *Apdu {
	if x != nil {
		if x, ok := x.Body.(*TransmitRequest_Apdu); ok {
			return x.Apdu
		}
	}
	return nil
}

func (x *TransmitRequest) GetRaw() []byte {
	if x != nil {
		if x, ok := x.Body.(*TransmitRequest_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

type isTransmitRequest_Body interface {
	isTransmitRequest_Body()
}

type TransmitRequest_Apdu struct {
	Apdu *Apdu `protobuf:"bytes,1,opt,name=apdu,proto3,oneof"`
}

type TransmitRequest_Raw struct {
	Raw []byte `protobuf:"bytes,2,opt,name=raw,proto3,oneof"`
}

func (*TransmitRequest_Apdu) isTransmitRequest_Body() {}

func (*TransmitRequest_Raw) isTransmitRequest_Body() {}

type TransmitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*TransmitResponse_Apdu
	//	*TransmitResponse_Raw
	Body          isTransmitResponse_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransmitResponse) Reset() {
	*x = TransmitResponse{}
	mi := &file_cardrelay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransmitResponse) ProtoMessage() {}

func (x *TransmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cardrelay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransmitResponse.ProtoReflect.Descriptor instead.
func (*TransmitResponse) Descriptor() ([]byte, []int) {
	return file_cardrelay_proto_rawDescGZIP(), []int{5}
}

func (x *TransmitResponse) GetBody() isTransmitResponse_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *TransmitResponse) GetApdu() *ApduResponse {
	if x != nil {
		if x, ok := x.Body.(*TransmitResponse_Apdu); ok {
			return x.Apdu
		}
	}
	return nil
}

func (x *TransmitResponse) GetRaw() []byte {
	if x != nil {
		if x, ok := x.Body.(*TransmitResponse_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

type isTransmitResponse_Body interface {
	isTransmitResponse_Body()
}

type TransmitResponse_Apdu struct {
	Apdu *ApduResponse `protobuf:"bytes,1,opt,name=apdu,proto3,oneof"`
}

type TransmitResponse_Raw struct {
	Raw []byte `protobuf:"bytes,2,opt,name=raw,proto3,oneof"`
}

func (*TransmitResponse_Apdu) isTransmitResponse_Body() {}

func (*TransmitResponse_Raw) isTransmitResponse_Body() {}

// ErrorResponse signals a server-side problem with the most recent
// request — the stream may continue if the client wants to retry.
// For terminal errors the server closes the stream after sending
// this.
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Kind          ErrorResponse_Kind     `protobuf:"varint,2,opt,name=kind,proto3,enum=cardrelay.v1.ErrorResponse_Kind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_cardrelay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cardrelay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_cardrelay_proto_rawDescGZIP(), []int{6}
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetKind() ErrorResponse_Kind {
	if x != nil {
		return x.Kind
	}
	return ErrorResponse_UNKNOWN
}

// Apdu is the parsed form of an ISO 7816-4 command APDU.
type Apdu struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Cla   uint32                 `protobuf:"varint,1,opt,name=cla,proto3" json:"cla,omitempty"`
	Ins   uint32                 `protobuf:"varint,2,opt,name=ins,proto3" json:"ins,omitempty"`
	P1    uint32                 `protobuf:"varint,3,opt,name=p1,proto3" json:"p1,omitempty"`
	P2    uint32                 `protobuf:"varint,4,opt,name=p2,proto3" json:"p2,omitempty"`
	Data  []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	// Le encoded the same way apdu.Command.Le is in the Go API:
	//
	//	-1: no Le (case 1 / case 3)
	//	 0: Le=256 (case 2 / case 4 short)
	//	1..256: explicit Le (256 indicates Le=00 short or Le=0000 ext)
	//
	// The Go side converts this to the wire byte during encoding.
	Le int32 `protobuf:"varint,6,opt,name=le,proto3" json:"le,omitempty"`
	// ExtendedLength forces extended-length encoding even when the
	// payload would fit in short form. Mirrors apdu.Command.
	ExtendedLength bool `protobuf:"varint,7,opt,name=extended_length,json=extendedLength,proto3" json:"extended_length,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Apdu) Reset() {
	*x = Apdu{}
	mi := &file_cardrelay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Apdu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Apdu) ProtoMessage() {}

func (x *Apdu) ProtoReflect() protoreflect.Message {
	mi := &file_cardrelay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Apdu.ProtoReflect.Descriptor instead.
func (*Apdu) Descriptor() ([]byte, []int) {
	return file_cardrelay_proto_rawDescGZIP(), []int{7}
}

func (x *Apdu) GetCla() uint32 {
	if x != nil {
		return x.Cla
	}
	return 0
}

func (x *Apdu) GetIns() uint32 {
	if x != nil {
		return x.Ins
	}
	return 0
}

func (x *Apdu) GetP1() uint32 {
	if x != nil {
		return x.P1
	}
	return 0
}

func (x *Apdu) GetP2() uint32 {
	if x != nil {
		return x.P2
	}
	return 0
}

func (x *Apdu) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Apdu) GetLe() int32 {
	if x != nil {
		return x.Le
	}
	return 0
}

func (x *Apdu) GetExtendedLength() bool {
	if x != nil {
		return x.ExtendedLength
	}
	return false
}

// ApduResponse is the parsed form of a response APDU.
type ApduResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Sw1           uint32                 `protobuf:"varint,2,opt,name=sw1,proto3" json:"sw1,omitempty"`
	Sw2           uint32                 `protobuf:"varint,3,opt,name=sw2,proto3" json:"sw2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApduResponse) Reset() {
	*x = ApduResponse{}
	mi := &file_cardrelay_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApduResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApduResponse) ProtoMessage() {}

func (x *ApduResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cardrelay_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApduResponse.ProtoReflect.Descriptor instead.
func (*ApduResponse) Descriptor() ([]byte, []int) {
	return file_cardrelay_proto_rawDescGZIP(), []int{8}
}

func (x *ApduResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApduResponse) GetSw1() uint32 {
	if x != nil {
		return x.Sw1
	}
	return 0
}

func (x *ApduResponse) GetSw2() uint32 {
	if x != nil {
		return x.Sw2
	}
	return 0
}

var File_cardrelay_proto protoreflect.FileDescriptor

const file_cardrelay_proto_rawDesc = "" +
	"\n" +
	"\x0fcardrelay.proto\x12\fcardrelay.v1\"\x88\x01\n" +
	"\rClientMessage\x122\n" +
	"\x05hello\x18\x01 \x01(\v2\x1a.cardrelay.v1.HelloRequestH\x00R\x05hello\x12;\n" +
	"\btransmit\x18\x02 \x01(\v2\x1d.cardrelay.v1.TransmitRequestH\x00R\btransmitB\x06\n" +
	"\x04body\"\xbf\x01\n" +
	"\rServerMessage\x123\n" +
	"\x05hello\x18\x01 \x01(\v2\x1b.cardrelay.v1.HelloResponseH\x00R\x05hello\x12<\n" +
	"\btransmit\x18\x02 \x01(\v2\x1e.cardrelay.v1.TransmitResponseH\x00R\btransmit\x123\n" +
	"\x05error\x18\x03 \x01(\v2\x1b.cardrelay.v1.ErrorResponseH\x00R\x05errorB\x06\n" +
	"\x04body\"Q\n" +
	"\fHelloRequest\x12\x16\n" +
	"\x06reader\x18\x01 \x01(\tR\x06reader\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\rR\x0fprotocolVersion\"R\n" +
	"\rHelloResponse\x12\x16\n" +
	"\x06reader\x18\x01 \x01(\tR\x06reader\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\rR\x0fprotocolVersion\"W\n" +
	"\x0fTransmitRequest\x12(\n" +
	"\x04apdu\x18\x01 \x01(\v2\x12.cardrelay.v1.ApduH\x00R\x04apdu\x12\x12\n" +
	"\x03raw\x18\x02 \x01(\fH\x00R\x03rawB\x06\n" +
	"\x04body\"`\n" +
	"\x10TransmitResponse\x120\n" +
	"\x04apdu\x18\x01 \x01(\v2\x1a.cardrelay.v1.ApduResponseH\x00R\x04apdu\x12\x12\n" +
	"\x03raw\x18\x02 \x01(\fH\x00R\x03rawB\x06\n" +
	"\x04body\"\xce\x01\n" +
	"\rErrorResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x124\n" +
	"\x04kind\x18\x02 \x01(\x0e2 .cardrelay.v1.ErrorResponse.KindR\x04kind\"m\n" +
	"\x04Kind\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\r\n" +
	"\tNO_READER\x10\x01\x12\x0f\n" +
	"\vREADER_GONE\x10\x02\x12\x14\n" +
	"\x10PROTOCOL_VERSION\x10\x03\x12\r\n" +
	"\tTRANSPORT\x10\x04\x12\x13\n" +
	"\x0fINVALID_REQUEST\x10\x05\"\x97\x01\n" +
	"\x04Apdu\x12\x10\n" +
	"\x03cla\x18\x01 \x01(\rR\x03cla\x12\x10\n" +
	"\x03ins\x18\x02 \x01(\rR\x03ins\x12\x0e\n" +
	"\x02p1\x18\x03 \x01(\rR\x02p1\x12\x0e\n" +
	"\x02p2\x18\x04 \x01(\rR\x02p2\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x0e\n" +
	"\x02le\x18\x06 \x01(\x05R\x02le\x12'\n" +
	"\x0fextended_length\x18\a \x01(\bR\x0eextendedLength\"F\n" +
	"\fApduResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x10\n" +
	"\x03sw1\x18\x02 \x01(\rR\x03sw1\x12\x10\n" +
	"\x03sw2\x18\x03 \x01(\rR\x03sw22T\n" +
	"\tCardRelay\x12G\n" +
	"\aSession\x12\x1b.cardrelay.v1.ClientMessage\x1a\x1b.cardrelay.v1.ServerMessage(\x010\x01BNZLgithub.com/PeculiarVentures/scp/transport/grpc/proto/cardrelayv1;cardrelayv1b\x06proto3"

var (
	file_cardrelay_proto_rawDescOnce sync.Once
	file_cardrelay_proto_rawDescData []byte
)

func file_cardrelay_proto_rawDescGZIP() []byte {
	file_cardrelay_proto_rawDescOnce.Do(func() {
		file_cardrelay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cardrelay_proto_rawDesc), len(file_cardrelay_proto_rawDesc)))
	})
	return file_cardrelay_proto_rawDescData
}

var file_cardrelay_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cardrelay_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cardrelay_proto_goTypes = []any{
	(ErrorResponse_Kind)(0),  // 0: cardrelay.v1.ErrorResponse.Kind
	(*ClientMessage)(nil),    // 1: cardrelay.v1.ClientMessage
	(*ServerMessage)(nil),    // 2: cardrelay.v1.ServerMessage
	(*HelloRequest)(nil),     // 3: cardrelay.v1.HelloRequest
	(*HelloResponse)(nil),    // 4: cardrelay.v1.HelloResponse
	(*TransmitRequest)(nil),  // 5: cardrelay.v1.TransmitRequest
	(*TransmitResponse)(nil), // 6: cardrelay.v1.TransmitResponse
	(*ErrorResponse)(nil),    // 7: cardrelay.v1.ErrorResponse
	(*Apdu)(nil),             // 8: cardrelay.v1.Apdu
	(*ApduResponse)(nil),     // 9: cardrelay.v1.ApduResponse
}
var file_cardrelay_proto_depIdxs = []int32{
	3, // 0: cardrelay.v1.ClientMessage.hello:type_name -> cardrelay.v1.HelloRequest
	5, // 1: cardrelay.v1.ClientMessage.transmit:type_name -> cardrelay.v1.TransmitRequest
	4, // 2: cardrelay.v1.ServerMessage.hello:type_name -> cardrelay.v1.HelloResponse
	6, // 3: cardrelay.v1.ServerMessage.transmit:type_name -> cardrelay.v1.TransmitResponse
	7, // 4: cardrelay.v1.ServerMessage.error:type_name -> cardrelay.v1.ErrorResponse
	8, // 5: cardrelay.v1.TransmitRequest.apdu:type_name -> cardrelay.v1.Apdu
	9, // 6: cardrelay.v1.TransmitResponse.apdu:type_name -> cardrelay.v1.ApduResponse
	0, // 7: cardrelay.v1.ErrorResponse.kind:type_name -> cardrelay.v1.ErrorResponse.Kind
	1, // 8: cardrelay.v1.CardRelay.Session:input_type -> cardrelay.v1.ClientMessage
	2, // 9: cardrelay.v1.CardRelay.Session:output_type -> cardrelay.v1.ServerMessage
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_cardrelay_proto_init() }
func file_cardrelay_proto_init() {
	if File_cardrelay_proto != nil {
		return
	}
	file_cardrelay_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_Hello)(nil),
		(*ClientMessage_Transmit)(nil),
	}
	file_cardrelay_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_Hello)(nil),
		(*ServerMessage_Transmit)(nil),
		(*ServerMessage_Error)(nil),
	}
	file_cardrelay_proto_msgTypes[4].OneofWrappers = []any{
		(*TransmitRequest_Apdu)(nil),
		(*TransmitRequest_Raw)(nil),
	}
	file_cardrelay_proto_msgTypes[5].OneofWrappers = []any{
		(*TransmitResponse_Apdu)(nil),
		(*TransmitResponse_Raw)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cardrelay_proto_rawDesc), len(file_cardrelay_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cardrelay_proto_goTypes,
		DependencyIndexes: file_cardrelay_proto_depIdxs,
		EnumInfos:         file_cardrelay_proto_enumTypes,
		MessageInfos:      file_cardrelay_proto_msgTypes,
	}.Build()
	File_cardrelay_proto = out.File
	file_cardrelay_proto_goTypes = nil
	file_cardrelay_proto_depIdxs = nil
}
