package securitydomain_test

import (
	"context"
	"fmt"

	"github.com/PeculiarVentures/scp/scp03"
	"github.com/PeculiarVentures/scp/securitydomain"
	"github.com/PeculiarVentures/scp/transport"
)

// ExampleSession_PutSCP03Key shows the canonical key-rotation flow:
// open a Security Domain session with the card's current SCP03 keys,
// then install a new SCP03 key set that supersedes them. After this
// completes successfully on the card, the previous key set is no
// longer accepted; subsequent sessions must authenticate with the
// new keys.
//
// PutSCP03Key requires an authenticated session that exposes the
// session DEK — either an SCP03 session (DEK derived from the
// pre-shared key set) or an OCE-authenticated SCP11a/c session
// (DEK derived from the dual-ECDH). SCP11b cannot drive this
// operation because it does not authenticate the host to the card.
//
// This example is illustrative; it does not run end-to-end because
// the in-tree mock card returns 6D00 to PUT KEY (the mock covers
// SCP handshake and read paths but not the management surface).
// Against real YubiKey hardware over a transport/pcsc reader the
// same code completes the rotation.
func ExampleSession_PutSCP03Key() {
	ctx := context.Background()
	var t transport.Transport // transport/pcsc, transport/grpc, etc.

	// Open the SD over SCP03 with the current key set. FactoryYubiKeyConfig
	// targets KVN 0xFF (factory keys); use a hand-built scp03.Config with
	// caller-supplied keys for the post-rotation case.
	sd, err := securitydomain.OpenSCP03(ctx, t, scp03.FactoryYubiKeyConfig())
	if err != nil {
		fmt.Println("open:", err)
		return
	}
	defer sd.Close()

	// New 16-byte AES-128 key set. In production these are generated by
	// a key-management system (HSM, key ceremony output, etc.), not by
	// any code that runs on the host.
	newKeys := scp03.StaticKeys{
		ENC: make([]byte, 16),
		MAC: make([]byte, 16),
		DEK: make([]byte, 16),
	}

	// Install at the SCP03 key class (KID = 0x01) under KVN 0x01,
	// replacing the factory key set at KVN 0xFF. After this call
	// returns nil, subsequent SCP03 sessions must use newKeys with
	// KeyVersion = 0x01.
	ref := securitydomain.NewKeyReference(securitydomain.KeyIDSCP03, 0x01)
	if err := sd.PutSCP03Key(ctx, ref, newKeys, 0xFF); err != nil {
		fmt.Println("put key:", err)
		return
	}
}
