package session

import (
	"crypto/x509"
	"testing"
)

// TestExtractCardPublicKey_ChainLeafFirst confirms the try-each
// fallback validates a chain whose entries arrive in leaf-first
// order (common for chains generated by generic X.509 tooling). The
// fast path checks leaf-last; this test exercises the fallback that
// iterates each cert as the candidate leaf.
func TestExtractCardPublicKey_ChainLeafFirst(t *testing.T) {
	rootDER, interDER, leafDER := makeChain(t)
	rootCert, _ := x509.ParseCertificate(rootDER)
	roots := x509.NewCertPool()
	roots.AddCert(rootCert)

	// Reverse order: leaf first, then intermediate. The fast path
	// (try leaf-last = the intermediate) will fail; the try-each
	// fallback should still find a valid ordering.
	bundle := buildBF21(leafDER, interDER)

	key, err := extractCardPublicKey(bundle, roots)
	if err != nil {
		t.Fatalf("leaf-first chain should validate via try-each fallback: %v", err)
	}
	if key == nil {
		t.Fatal("expected non-nil ECDH key")
	}
}

// TestExtractCardPublicKey_ChainLeafFirst_WithRoot confirms the
// fallback also handles the all-three-out-of-order case
// (leaf, root, intermediate — pathological but possible).
func TestExtractCardPublicKey_ChainLeafFirst_WithRoot(t *testing.T) {
	rootDER, interDER, leafDER := makeChain(t)
	rootCert, _ := x509.ParseCertificate(rootDER)
	roots := x509.NewCertPool()
	roots.AddCert(rootCert)

	bundle := buildBF21(leafDER, rootDER, interDER)

	key, err := extractCardPublicKey(bundle, roots)
	if err != nil {
		t.Fatalf("scrambled chain should still validate: %v", err)
	}
	if key == nil {
		t.Fatal("expected non-nil ECDH key")
	}
}
