package session

import (
	"context"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"strings"
	"testing"

	"github.com/PeculiarVentures/scp/trust"
)

// TestTrustPolicy_LeafFirstChain_Validates confirms the trust-policy
// validation path now retries with each cert as the candidate leaf
// when the fast (leaf-last) ordering fails. Earlier the trust-policy
// path called ValidateSCP11Chain once with the input ordering; chains
// generated by generic X.509 tooling (typically leaf-first) failed
// even though the certs were valid.
func TestTrustPolicy_LeafFirstChain_Validates(t *testing.T) {
	rootDER, interDER, leafDER := makeChain(t)
	rootCert, _ := x509.ParseCertificate(rootDER)
	roots := x509.NewCertPool()
	roots.AddCert(rootCert)

	bundle := buildBF21(leafDER, interDER) // leaf FIRST

	sess := &Session{
		config: &Config{
			CardTrustPolicy: &trust.Policy{Roots: roots},
		},
	}
	if err := sess.validateCardCertChain(bundle); err != nil {
		t.Fatalf("trust-policy path should validate leaf-first chain via try-each fallback: %v", err)
	}
	if sess.cardStaticPubKey == nil {
		t.Fatal("validated chain should have populated cardStaticPubKey")
	}
}

// TestTrustPolicy_SingleCertChain_StillFails confirms the try-each
// fallback doesn't accidentally make the single-cert "no
// intermediate" case succeed when it shouldn't.
func TestTrustPolicy_SingleCertChain_StillFails(t *testing.T) {
	rootDER, _, leafDER := makeChain(t)
	rootCert, _ := x509.ParseCertificate(rootDER)
	roots := x509.NewCertPool()
	roots.AddCert(rootCert)

	bundle := buildBF21(leafDER) // intermediate intentionally omitted

	sess := &Session{
		config: &Config{
			CardTrustPolicy: &trust.Policy{Roots: roots},
		},
	}
	err := sess.validateCardCertChain(bundle)
	if err == nil {
		t.Fatal("leaf-only bundle should not validate when intermediate is required")
	}
}

// TestCustomValidator_RejectsNonP256Key confirms the post-validator
// invariant check rejects keys on the wrong curve, even when the
// validator accepts. SCP11 mandates P-256; any other curve breaks
// the protocol regardless of the trust decision.
func TestCustomValidator_RejectsNonP256Key(t *testing.T) {
	// Generate a P-384 key — passes the validator's "accept any
	// key" logic but should be rejected by the curve invariant.
	priv, err := ecdsa.GenerateKey(elliptic.P384(), rand.Reader)
	if err != nil {
		t.Fatalf("ecdsa.GenerateKey P-384: %v", err)
	}

	pol := &trust.Policy{
		CustomValidator: func(_ []byte) (*trust.Result, error) {
			return &trust.Result{PublicKey: &priv.PublicKey}, nil
		},
	}

	sess := &Session{
		config: &Config{CardTrustPolicy: pol},
	}
	err = sess.validateCardCertChain([]byte("ignored"))
	if err == nil {
		t.Fatal("validateCardCertChain should reject P-384 key from custom validator")
	}
	if !strings.Contains(err.Error(), "P-256") {
		t.Errorf("error should mention P-256 invariant; got: %v", err)
	}
}

// TestCustomValidator_AcceptsP256Key confirms the post-validator
// invariant check is permissive for the right curve.
func TestCustomValidator_AcceptsP256Key(t *testing.T) {
	priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatalf("ecdsa.GenerateKey: %v", err)
	}
	pol := &trust.Policy{
		CustomValidator: func(_ []byte) (*trust.Result, error) {
			return &trust.Result{PublicKey: &priv.PublicKey}, nil
		},
	}
	sess := &Session{
		config: &Config{CardTrustPolicy: pol},
	}
	if err := sess.validateCardCertChain([]byte("ignored")); err != nil {
		t.Fatalf("P-256 key from validator should be accepted: %v", err)
	}
}

// Avoid unused-import warnings on context if we end up not using it.
var _ = context.Background
